// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:stock_data_entry/models/dividend_rate.dart';
import 'package:stock_data_entry/models/price_range.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DividendRateAdapter());
    registerAdapter(PriceRangeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DividendRateAdapter());
    registerAdapter(PriceRangeAdapter());
  }
}
